In [21]:
import numpy as np
import array
import sys

In [18]:
# 1 и 2 задание

a1 = array.array('b', [1,2,3])
print(sys.getsizeof(a1))
print(type(a1))

a1 = array.array('B', [1,0,1])
print(sys.getsizeof(a1))
print(type(a1))

a1 = array.array('h', [1,2,3])
print(sys.getsizeof(a1))
print(type(a1))

a1 = array.array('H', [1,2,3])
print(sys.getsizeof(a1))
print(type(a1))

a1 = array.array('i', [1,2,3])
print(sys.getsizeof(a1))
print(type(a1))

a1 = array.array('I', [1,2,3])
print(sys.getsizeof(a1))
print(type(a1))

a1 = array.array('l', [1,2,3])
print(sys.getsizeof(a1))
print(type(a1))

a1 = array.array('L', [1,2,3])
print(sys.getsizeof(a1))
print(type(a1))

a1 = array.array('q', [1,2,3])
print(sys.getsizeof(a1))
print(type(a1))

a1 = array.array('Q', [1,2,3])
print(sys.getsizeof(a1))
print(type(a1))

a1 = array.array('f', [1.03,2.03,3.03])
print(sys.getsizeof(a1))
print(type(a1))

a1 = array.array('d', [1.23,2.23,3.23])
print(sys.getsizeof(a1))
print(type(a1))

83
<class 'array.array'>
83
<class 'array.array'>
86
<class 'array.array'>
86
<class 'array.array'>
92
<class 'array.array'>
92
<class 'array.array'>
92
<class 'array.array'>
92
<class 'array.array'>
104
<class 'array.array'>
104
<class 'array.array'>
92
<class 'array.array'>
104
<class 'array.array'>


In [31]:
# 3 задание
x = np.arange(0,1,0.2)
print(x)

[0.  0.2 0.4 0.6 0.8]


In [28]:
# 4 задание
np.random.seed(1)

x = np.random.uniform(0,1,5)
print(x)

[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
 1.46755891e-01]


In [30]:
# 5 задание
np.random.seed(1)

x = np.random.standard_normal(5)
print(x)

[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763]


In [36]:
# 6 задание
np.random.seed(1)

x = np.random.randint(0, 10, 5)
print(x)

[5 8 9 5 0]


In [60]:
# 7 задание
x = np.array([range(i*4, i*4+4) for i in range(3)])
print(x)

print(x[:2,:3])

print(x[:3,1:2])

print(x[::-1,::-1])

print(x[:,1:2])

print(x[2:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2]
 [4 5 6]]
[[1]
 [5]
 [9]]
[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]
[[1]
 [5]
 [9]]
[[ 8  9 10 11]]


In [61]:
#8 задание
x = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11]
])

copy = x[:3, :3].copy()

print(x)
print(copy)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]


In [68]:
#9 задание
x = np.array([1,2,3])
print(x[np.newaxis, :])

print(x[:, np.newaxis])

[[1 2 3]]
[[1]
 [2]
 [3]]


In [70]:
#10 задание

a = np.array([1,2,3])

b = np.array([4,5,6])

print(np.dstack((a,b)))

[[[1 4]
  [2 5]
  [3 6]]]


In [80]:
#11 задание 
arr = np.arange(16).reshape(4, 4)
print(arr)

print(np.split(arr,2,axis = 0))
print(np.split(arr,2,axis = 1))

print(np.vsplit(arr,2))

print(np.hsplit(arr,2))

arr = np.arange(24).reshape(2,3,4)

print(arr)
print(np.dsplit(arr,2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]]]), array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]])]


In [87]:
#12 задание
arr = np.arange(12)
print(arr)

print(arr*2)

print(arr + arr)

print(arr/2)

print(arr-1)

print(arr%2)

print(arr//3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  2  4  6  8 10 12 14 16 18 20 22]
[ 0  2  4  6  8 10 12 14 16 18 20 22]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5]
[-1  0  1  2  3  4  5  6  7  8  9 10]
[0 1 0 1 0 1 0 1 0 1 0 1]
[0 0 0 1 1 1 2 2 2 3 3 3]
